spring:
  application:
    name: springdataredis_demo
#Redis相关配置
redis:
  host: 127.0.0.1
  port: 6379
  #password:224544   由于windows这个Redis中没有设置密码，所以不需要
  database: 0   #0号数据库，默认提供了16个数据库 可以改的(在redis.windows.conf文件里)且如何命令切换呢？--select 序号
  jedis:
  #Redis连接池配置  同mysql连接池这种
  pool:
    max-active: 8 #最大连接数量
    max-wait: 1ms #连接池最大阻塞等待时间
    max-idle: 4 #连接池中的最大空闲连接
    min-idle: 0 #连接池中的最小空闲连接
